# Project: test
# Makefile created by Red Panda C++ 1.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = test_private.res
OBJ      = main.o parser.o HLS.o $(RES)
LINKOBJ  = main.o parser.o HLS.o $(RES)
CLEANOBJ  =  main.o parser.o HLS.o test_private.res test.exe
LIBS     = 
INCS     =  
CXXINCS  =  
BIN      = test.exe
CXXFLAGS = $(CXXINCS)  -g3 -pipe -Wall -Wextra -D__DEBUG__
CFLAGS   = $(INCS)  -g3 -pipe -Wall -Wextra -D__DEBUG__
RM       = del /q /f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(CLEANOBJ) > NUL 2>&1

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp parser.h HLS.h
	$(CPP) -c C:/Users/18064/Documents/projects/test/main.cpp -o main.o $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=utf-8

parser.o: parser.cpp parser.h
	$(CPP) -c C:/Users/18064/Documents/projects/test/parser.cpp -o parser.o $(CXXFLAGS) 

HLS.o: HLS.cpp parser.h HLS.h
	$(CPP) -c C:/Users/18064/Documents/projects/test/HLS.cpp -o HLS.o $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=utf-8

test_private.res: test_private.rc 
	$(WINDRES) -i test_private.rc --input-format=rc -o test_private.res -O coff 

